project:
  type: website
  output-dir: _site

website:
  title: "Yojiro Ito"
  navbar:
    right:
      - text: "Home"
        href: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
